# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Blog tập nuôi thỏ
logo:               https://github.com/greedytofu/fachinformatiker-forum/blob/gh-pages/logo.jpg?raw=true# Logo image URL
email:              tiep@tofu.am
description:        Tofu nuôi thỏ
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://tofu.am' # The base hostname & protocol for your site
github_username:    tiep
twitter_username:   tiep
instagram_username: tiep

markdown:  kramdown
permalink: pretty
paginate:  13
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-feed

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:             Tập nuôi thỏ
    bio:              Blog viết về nuôi thỏ và hướng dẫn cách làm trại thỏ hay phương pháp nuôi thỏ tốt.
    gravatar:         https://en.gravatar.com/forsthaus
    email:            joerg@reuter.sc
    website:          https://tofu.am
    github_username:  tiep
    twitter_username: tiep
